# Generated by Django 5.1.1 on 2024-12-05 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_category_options_account_owner'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='invited_contacts',
            field=models.ManyToManyField(blank=True, related_name='events', to='accounts.account'),
        ),
    ]
